### ISSUE TITLE
Error when attempting to give valid kudos

### ISSUE THREAD

**Issue by davelush** [davelush/slack-bot-kudos#19]
Message as follows;

```commandLine
:star: <@AAAAAAAA> for provoking discussion by Team-name yesterday
```

And stack trace

```commandLine
  Traceback (most recent call last):
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/flask_restful/__init__.py", line 458, in wrapper
    resp = resource(*args, **kwargs)
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/flask_restful/__init__.py", line 573, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/app/org/davelush/slack_bot/slack_event_handler.py", line 70, in post
    return hears(self.py_bot)
  File "/app/org/davelush/slack_bot/slack_event_handler.py", line 58, in hears
    return event_handler(event_type, slack_event, py_bot)
  File "/app/org/davelush/slack_bot/slack_event_handler.py", line 21, in event_handler
    if sentiment.contains_emoji(text) and sentiment.contains_user(text):
  File "/app/org/davelush/kudos/sentiment.py", line 37, in contains_emoji
    return re.findall(p, text)
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/re.py", line 223, in findall
    return _compile(pattern, flags).findall(string)
TypeError: expected string or bytes-like object
```

**Comment by davelush** [comment]
This appears to happen when the bot has sat idle for a period of time and is worked around by a pod restart
